[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["Khionu Sybiern <abstractkitty@iamtrue.net>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3.8"
itertools = "0.8.0"
lazy_static = "1.3.0"
rayon = "1.1.0"
